version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_DATABASE: clientdb,voituredb
    ports:
      - "3306:3306"
  controle-server:
    container_name: controle-server
    build: ./ControleServer
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 3
  controle-client:
    container_name: controle-client
    build: ./ControleClient
    ports:
      - "8081:8081"
    expose:
      - "8081"

    depends_on:
        controle-server:
            condition: service_healthy
        mysql:
            condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3


  controle-car:
    container_name: controle-car
    build: ./ControleCar
    ports:
      - "8082:8082"
    expose:
      - "8082"

    depends_on:
      controle-server:
        condition: service_healthy
      mysql:
        condition: service_started
      controle-client:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3

  controle-gateway:
    container_name: controle-gateway
    build: ./ControleGateway
    ports:
      - "8888:8888"
    expose:
        - "8888"
    depends_on:
      controle-server:
        condition: service_healthy



  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"

