version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  controle-server:
    container_name: controle-server
    image: controle-server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 3

  controle-client:
    container_name: controle-client
    image: controle-client
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      - controle-server
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 3

  controle-car:
    container_name: controle-car
    image: controle-car
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      - controle-server
      - mysql
      - controle-client
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 3

  controle-gateway:
    container_name: controle-gateway
    image: controle-gateway  # Assuming you have an image named "controle-gateway"
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      - controle-server
